language: python

python:
  - 3.4

sudo: false

branches:
  except:
    - master

install:
    - pip install coveralls
    - pip install -r requirements.txt

script: nosetests

after_success: coveralls
