# case sensitive
settings = {
    'categories': [
        'TV|SD|VOSTFR', 'TV|HD|VOSTFR', 'TV|SD|VF', 'TV|HD|VF', 'TV|PACK|FR',
        'TV|PACK|VOSTFR', 'TV|EMISSIONS', 'DOCS', 'ANIME', 'MOVIE|DVDR',
        'MOVIE|DVDRIP', 'MOVIE|BDRIP', 'MOVIE|VOSTFR', 'MOVIE|HD|720p',
        'MOVIE|HD|1080p', 'MOVIE|REMUXBR', 'MOVIE|FULLBR', 'PC|APP', 'PC|GAMES',
        'MUSIC|FLAC', 'MUSIC|MP3', 'MUSIC|CONCERT', 'EBOOKS',
    ],
    'order': [
        'ReleaseName', 'Time', 'Seeders', 'Leechers', 'Snatched', 'Size',
    ],
    'way': [
        'asc', 'desc',
    ],
    'search': [''],
    'genres': {
        'movies': {
            'Action': 1, 'Animation': 2, 'Arts Martiaux': 3, 'Aventure': 4,
            'Biopic': 5, 'Bollywood': 6, 'Classique': 7, 'Comédie': 8,
            'Comédie dramatique': 9, 'Comédie musicale': 10, 'Concert': 11,
            'Dessin animé': 12, 'Documentaire': 13, 'Drama': 14, 'Drame': 15,
            'Epouvante-horreur': 16, 'Erotique': 17, 'Espionnage': 18,
            'Expérimental': 19, 'Famille': 20, 'Fantastique': 21, 'Guerre': 22,
            'Historique': 23, 'Judiciaire': 24, 'Movie night': 25,
            'Musical': 26, 'Opera': 27, 'Péplum': 28, 'Policier': 29,
            'Romance': 30, 'Science fiction': 31, 'Show': 32, 'Sport event': 33,
            'Thriller': 34, 'Western': 35,
        },
        'music': {
            'Rock': 36, 'Electronic': 37, 'Pop': 38,
            'Folk, World, & Country': 39, 'Funk / Soul': 40, 'Jazz': 41,
            'Hip Hop': 42, 'Classical': 43, 'Reggae': 44, 'Latin': 45,
            'Stage & Screen': 46, 'Blues': 47, 'Non-Music': 48,
            'Children\'s': 49, 'Metal': 50,
        },
        'game': {
            'Action': 51, 'Action-Adventure': 52, 'Adventure': 53,
            'Baseball': 54, 'Basketball': 55, 'Billiards': 56,
            'Block-Breaking': 57, 'Bowling': 58, 'Boxing': 59, 'Brawler': 60,
            'Card Game': 61, 'Compilation': 62, 'Cricket': 63,
            'Driving/Racing': 64, 'Dual-Joystick Shooter': 65,
            'Educational': 66, 'Fighting': 67, 'First-Person Shooter': 68,
            'Fishing': 69, 'Fitness': 70, 'Football': 71, 'Gambling': 72,
            'Golf': 73, 'Hockey': 74, 'Flight Simulator': 75,
            'Light-Gun Shooter': 76, 'Minigame Collection': 77, 'MMORPG': 78,
            'MOBA': 79, 'Music/Rhythm': 80, 'Pinball': 81, 'Platformer': 82,
            'Puzzle': 83, 'Real-Time Strategy': 84, 'Role-Playing': 85,
            'Shoot \'Em Up': 86, 'Shooter': 87, 'Simulation': 88,
            'Skateboarding': 89, 'Snowboarding/Skiing': 90, 'Soccer': 91,
            'Sports': 92, 'Strategy': 93, 'Surfing': 94, 'Tennis': 95,
            'Text Adventure': 96, 'Track & Field': 97, 'Trivia/Board Game': 98,
            'Vehicular Combat': 99, 'Wrestling': 100,
        },
        'anime': {
            'Action': 101, 'Adventure': 102, 'Cars': 103, 'Comedy': 104,
            'Dementia': 105, 'Demons': 106, 'Drama': 107, 'Ecchi': 108,
            'Fantasy': 109, 'Game': 110, 'Harem': 111,
            'Hentai': 112, 'Historical': 113, 'Horror': 114, 'Josei': 115,
            'Kids': 116, 'Magic': 117, 'Martial Arts': 118, 'Mecha': 119,
            'Military': 120, 'Music': 121, 'Mystery': 122, 'Parody': 123,
            'Police': 124, 'Psychological': 125, 'Romance': 126, 'Samurai': 127,
            'School': 128, 'Sci-Fi': 129, 'Seinen': 130, 'Shoujo': 131,
            'Shoujo Ai': 132, 'Shounen': 133, 'Shounen Ai': 134,
            'Slice of Life': 135, 'Space': 136, 'Sports': 137,
            'Super Power': 138, 'Supernatural': 139, 'Thriller': 140,
            'Vampire': 141, 'Yaoi': 142, 'Yuri': 143,
        },
        'tv': {
            'Action': 144, 'Animation': 145, 'Arts Martiaux': 146,
            'Aventure': 147, 'Biopic': 148, 'Bollywood': 149, 'Classique': 150,
            'Comédie': 151, 'Comédie dramatique': 152, 'Comédie musicale': 153,
            'Concert': 154, 'Dessin animé': 155, 'Documentaire': 156,
            'Drama': 157, 'Drame': 158, 'Epouvante-horreur': 159,
            'Erotique': 160, 'Espionnage': 161, 'Expérimental': 162,
            'Famille': 163, 'Fantastique': 164, 'Guerre': 165,
            'Historique': 166, 'Judiciaire': 167, 'Movie night': 168,
            'Musical': 169, 'Opera': 170, 'Péplum': 171, 'Policier': 172,
            'Romance': 173, 'Science fiction': 174, 'Show': 175,
            'Sport event': 176, 'Thriller': 177, 'Western': 178,
        },
    },
}

search_params = {
    'search': 'search',
    'cat[]': 'categories',
    'order': 'order',
    'way': 'way',
    'genres[]': 'genres'
}
